### ISSUE TITLE
Double health bar status on target

### ISSUE THREAD

**Issue by Daliniero** [Ko0z/zUI#15]
Does any1 know how to fix double health bar status on target?
![Screenshot_1](https://github.com/Ko0z/zUI/assets/43819736/dba86913-78d3-45f8-8177-ad016a06c7d2)

**Comment by MasterBruin** [comment]
Is this on Turtle WoW?

**Comment by Daliniero** [comment]
yes it is!

**Comment by MasterBruin** [comment]
I also tested the mod. I think this a client side feature from the turtle devs.
This should be only fixed when the mod author updates the mod for turtle client.

**Comment by Daliniero** [comment]
so I should report this to turtle wow gms?

**Comment by MasterBruin** [comment]
GMs won't do anything about that.

**Comment by Ko0z** [comment]
There was a long long time ago I wrote this. Quick info in case you dont know, originally in 1.12, the players did not get numeric health values from the client or server, therefore everyone used an addon like MobHealth which estimates the health on each mob based on damage vs percentage decrease values and stores them locally.

I have never played Turtle but it sounds like TurtleWow has some modified client which probably feeds the values directly to the client. 

I want to remeber that you can type /MH or something and then be able to disable MobHealth. And normally I think you can disable the numeric health in the original wow settings in game if that is better. I think you should try to disable one or the other if possible. Make sure that you dont have any other mob health addon like Mob Info or whatever it was called. Hope it helps.

**Comment by Ko0z** [comment]
Alright, got curious and downloaded turtle, I got a fix for you.

![image](https://github.com/Ko0z/zUI/assets/9639004/9b0a6d9e-8605-48e5-bb4c-8fd50425d054)

Altough, I think I will need to create a new option for this since it might be annoying for everyone not playing on turtleWoW. Going to fix it and push the new update ASAP today.

**Comment by Ko0z** [comment]
The update is out, 

Look at the bottom of the updated ReadMe for instructions and pictures, but in short:
- Disable 'Status Bar Text' in WoW Interface Options. (Only way to hide TurtleWoW Target Text for now)
- Enable 'Force Show Hp/Mp' in zUI Settings under Unitframes

Please report any issues if they arrise

**Comment by MasterBruin** [comment]
Wow, many thanks for the quick update! I will test it out tomorrow.

**Comment by Ko0z** [comment]
I have tested it a bit and it seems to work correctly so I'm going to close this. 

Feel free to reopen if you run into any issues!

**Comment by MasterBruin** [comment]
Yes, all the target values are flawless working, tyvm!
I wanted to ask, how do you enable the third actionbar in the mid, in one of your sceenshots or is this another addon?

**Comment by Ko0z** [comment]
@MasterBruin Great!

It was such a long time I made that feature had forgotten myself.. It's kinda unintuitive but if you uncheck BFA-Style in zUI settings and then disable "Show Bottom Right ActionBar" in Interface Options you get that.

I need to remake this to make it easier to understand for sure..

![image](https://github.com/Ko0z/zUI/assets/9639004/9da15e98-3c8a-4587-8f9b-0a2efa636be9)

![image](https://github.com/Ko0z/zUI/assets/9639004/ded2e49d-2489-42a4-9e37-cff4b0389467)

![image](https://github.com/Ko0z/zUI/assets/9639004/54b36342-2ce6-4ab8-98f4-27ab322393e1)

**Comment by MasterBruin** [comment]
Ahhh okay, it took me a while how to activate those, but now I got it. The ring menu is a pretty cool idea!

**Comment by aixiu** [comment]
> It was such a long time I made that feature had forgotten myself.. It's kinda unintuitive but if you uncheck BFA-Style in zUI settings and then disable "Show Bottom Right ActionBar" in Interface Options you get that.


![image](https://github.com/Ko0z/zUI/assets/8064012/cf66a4b7-6785-40b4-b218-5cc1113245ac)

After enabling the above mode, the experience bar does not appear to be displayed correctly.
