### ISSUE TITLE
HP bar always at max

### ISSUE THREAD

**Issue by Wiggen94** [Ko0z/zUI#16]
After the latest commit the player's health bar is always at max.

https://github.com/Ko0z/zUI/commit/f1c65ca85f8b167f5f72d7c02067ebb162c80dd7

The target bar however is correct, even when targeting the player.

EDIT: This  only happens when "Force show HP/MP" is enabled.

**Comment by Ko0z** [comment]
@Wiggen94 Wups, my bad, I will fix it right away, lol 

Thanks for reporting!

**Comment by Ko0z** [comment]
@Wiggen94 Should be resolved now, are you playing on TurtleWoW?

I removed the option to force show Hp/Mp since I found a better solution, so now you probably want to enabble "Show Status Text" in Interface Options again to show text on target frame.

**Comment by Wiggen94** [comment]
I am playing on TurtleWoW.
And yes, it works perfectly without force show hp/mp and enabling status text now.
