### ISSUE TITLE
icons in bottom-right action bar disappear

### ISSUE THREAD

**Issue by freedom-yuhf** [Ko0z/zUI#19]
hi ko0z, I found an issue in action bar, in BFA pattern, the icons in bottom-right action bar will disappear when using shift+2,3... to change the main action bar and click any button with mouse, don't know what happened, please fix it, thanks a lot~, using it in turtle wow, by the way.

ps: the enemy cast bar always shows spell process even when the target is not casting spell or be interrupted, can you do something about it?
![pic1](https://github.com/Ko0z/zUI/assets/56567834/0c1ff37b-249b-47bc-89db-cc9db401916c)

**Comment by Ko0z** [comment]
@freedom-yuhf Hello, thanks for the report and good explanation with pictures, I will look in to it asap.
