### ISSUE TITLE
Swing Timer

### ISSUE THREAD

**Issue by DecepUK** [Ko0z/zUI#2]
Would be good if there was an option for the swing timer to only show main hand swings.

**Comment by Ko0z** [comment]
@DecepUK Thanks for reporting, I will look at it!

**Comment by Ko0z** [comment]
@DecepUK This should be resolved in the latest update, the reason why I've been tinkering with this is becuase if you are a warrior for example and have flurry proc while you use the slam ability, the timer should reset no matter where the timer currently stands and immediately show the new correct timer of the slight faster flurry weapon speed! 

Thanks again for reporting, I'll close this one, but feel free to reopen it if there's anything else you might find! 👍
