### ISSUE TITLE
cooldown animation not visible

### ISSUE THREAD

**Issue by kurowi35** [Ko0z/zUI#20]
When using zui, cooldown animation is not visible, spell is not grayed out. Numbers do appear but ideally both should be visible.
Is it something that can be done?
See attached screenshot, charge spell is used. First one is zui, second is vanilla, no other addons loaded, third is omnicc (behavior unchanged with zui loaded).

![zui-cd](https://github.com/Ko0z/zUI/assets/142305490/8966fb2c-9623-4033-beeb-b76058881011)

**Comment by kurowi35** [comment]
Follow-up information : this bug is not present when i create another class; i tried with both night elves and taurens for a lvl 1 cooldown and only the warrior class has the bug so far.

**Comment by kurowi35** [comment]
Another follow up, it might be related to stances or forms shift, i have a druid who, when in bear form has no visible animation when an ability is in cooldown.

**Comment by Ko0z** [comment]
@kurowi35 Hey, thanks for the detailed report, I'm gonna look into it asap

**Comment by kurowi35** [comment]
Hey man, still having that issue, idk if you still maintain the addon or not

**Comment by Ko0z** [comment]
@kurowi35 Hey, alright damn. I will see if I get some spare time to look into this..

**Comment by Ko0z** [comment]
@kurowi35 alright, got a fix for you. 

Added a new option under "Cooldowns" in the zui menu. (type /zui in chat to show)
There's now a checkbox for "Show Cooldown Background Timer"

Let me know if this broke something else.

**Comment by kurowi35** [comment]
Hey, sorry for being persistent, i just really like your addon and didn't wanna switch for such a small inconvenience. After my last comment i actually ended up fixing it myself the same way you did in your last commit (eg - commenting --v:SetFrameLevel(4) in skins/actionbuttons.lua). So far i had no issues. Thanks for the actual fix though !
