### ISSUE TITLE
Druid mana bar when in bear form missing

### ISSUE THREAD

**Issue by mitjafelicijan** [Ko0z/zUI#23]
I have tried it and i see the same unitframe when in bear form or normal stance. Is there a setting I need to tick on. I am testing this on Turtle.

![image](https://github.com/Ko0z/zUI/assets/296714/3b88f44d-a203-415e-a817-cb1459908e8e)

![image](https://github.com/Ko0z/zUI/assets/296714/5d75c17a-5e62-49e7-b7ae-e213d1b644b5)

**Comment by Sunshineskt** [comment]
Hi, did you find out how to fix this?
