### ISSUE TITLE
Hotkeys

### ISSUE THREAD

**Issue by DecepUK** [Ko0z/zUI#3]
When disabling the zHotkeys component, it doesnt turn the default blizzard hotkey text back on.

**Comment by Ko0z** [comment]
@DecepUK Thank you for reporting this, I'll take a look at it!

**Comment by Ko0z** [comment]
@DecepUK Should be fixed now. However, turning off the zHotkey component will cause the keybind text to not update properly when bidning keys. So if it is the original hotkey font you wanted, I added an option for that under "Actionbars" option tab.

feel free to close this if you're happy with the outcome!

**Comment by DecepUK** [comment]
Nailed it, let me know if there's anything specific you want me to test!

**Comment by Ko0z** [comment]
@DecepUK Thank you! Yea sure, I will 👍
