### ISSUE TITLE
Please Respect The License

### ISSUE THREAD

**Issue by shagu** [Ko0z/zUI#4]
[pfUI](https://gitlab.com/shagu/pfUI) is Open-Source and MIT licensed, but you still have to give credits to the author. In case you haven't read it, here's the crucical a part of it:
```
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
```

The whole zUI.lua is basically a copy paste of the pfUI.lua. Some obvious examples would be:
https://github.com/Ko0z/zUI/blob/master/zUI.lua#L27-L61
https://gitlab.com/shagu/pfUI/blob/master/pfUI.lua#L20-54
And if you scroll further, like the whole addon/module/namespace structure of pfUI and its functions has just been renamed. Same with the configuration UI, the tables.lua, the libraries (well at least you give a credit in one of them) and many of the components... The list is endless.

Since we already had such a discussion on reddit about *your* improved unitframes, where you told me, that you usually always give credits makes this even worse.

Seeing this without giving credit and not respecting the license at all makes me sad.

**Comment by Ko0z** [comment]
@shagu I'm sorry that you feel that way, I've thought that I'd given you credits in more places than that. Your name is under author in the .toc file too but I guess I should make it more clear exactly what's been taken or heavily inspired from your addons. I will go over all the files and add proper credits. I will talk to you again once I've done that and see what you think. Shagu you are a god at this and you are one of my greatest inspiration, if you're not happy afterwards, I'll just delete those parts.

**Comment by shagu** [comment]
Thanks for https://github.com/Ko0z/zUI/commit/f8f36fa67c322e95780cd3ca1835df5b2245c558

It wasn't my intention having you add comments into every file though. It would just have been great to have a section somewhere in the readme, where you tell about where the origin of the project was, that it started as a fork or whatever. Also name the addon projects/authors where you took code from is most likely what other authors expect you to do aswell. A good example from a project (unrelated to addons) that started as a fork and became more and more independent would be https://github.com/mikebrady/shairport-sync#heritage

You might can get some inspiration from how he did it, maybe paired with a "Thanks to" section to mention the others ;)

Cheers

**Comment by Ko0z** [comment]
@shagu You are absolutely right, I've been slacking with the credits.. This project started out as a personal little modified project and as I implemented more stuff I forgot to give proper credits, and for that I'm sorry. It was never my intention to even share this at the beginning, but then I figured that maybe there's someone out there who would like to use it. You can see in the history of the .toc file that your name always has been there under "Author" but I agree that it wasn't enough.

I took a look at mikebrady's github and made a section for heritage and a special thank you in the ReadMe. You are the greatest addon developer I know and I promise you that I have never tried or had any intention to take credits for any of the work that derived from you.

**Comment by shagu** [comment]
Thank you very much. It looks good now.

> This project started out as a personal little modified project and as I implemented more stuff I forgot to give proper credits, and for that I'm sorry.

I understand, happens.

I think the first sentences of the README can be removed as they're duplicates now. :wink:
